# This travis.yml was built to:
#   - install ruby and nodejs
#   - run nodejs test
#   - lint javascript code
#   - check commit message style when in a PR
#   - deploy website when merged to master
# We defined the language to be ruby to benefit from bundle caching, it seems to be the only way to have it
# working well in travis.
# Then we install ruby and nodejs with rvm and nvm
# We also cache ./node_modules/
language: ruby
before_install:
  - 'git config --global user.email "algoliaplacesbot@users.noreply.github.com"'
  - 'git config --global user.name "algoliaplacesbot"'
  # https://github.com/travis-ci/travis-ci/issues/5092
  - '[ -f ./node_modules/.bin/which ] && mv ./node_modules/.bin/which ./node_modules/.bin/which-tmp'
  - rvm install 2.3.0
  - rvm use 2.3.0
  - '[ -f ./node_modules/.bin/which-tmp ] && mv ./node_modules/.bin/which-tmp ./node_modules/.bin/which'
  - nvm install 6
  - nvm use 6
gemfile: docs/Gemfile
script:
  - npm install
  - npm run test:ci
branches:
  only:
    - master
notifications:
  slack: algolia:wSMHl9gxKQ7cRvnOPUWE9esI
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
env:
  global:
    # CACHE_URL
    - secure: DDefJ0w7b8bulZZNCIpcrOnPR6Itfpr/eB6kBbzU2/MbYJSyHfe09OSYj8wjYOnGHzhTvSoT+IIshA6ncSlpuZLcAHVRGA5ShZYQU9uctfDcsWKFcXPKfZ1BFc2IIeoiNWgeI9yileBi6NYirknTwRK1BRHXPWOgOZaX/Bo+Qah4zKZTzdVKkw+uMPZFQII6wIZ1JIwLr3Il1laqUISpk+fSvxT/n3UNKPdN/GLk1hGdtl4km/dSpQaB2UTBZVd56NuaoBs1hDoZiVK+/6OQ1j/+sG0qs6anLgRmJnjMOrsbHMo8VBjSmUw5X+5Gg2zDrM11nsLiwsA/IgrS8fUqZtPeHPugro0rJJRvUT4macGPh/lRylzRv0LjTHfcf2pZVSgv7LI0WEVYyfPDjbA1dNTlSkexzsKlxrGeIB0LgaN87OirGgU/zuUC0Ew5ZnpE/4xk7maAOC02Rb0aPv4O3IVIRhjT0mHYrZRLi5nJxiAg31+ce4+WvDKC2TdOplb7vQ9LCJeAxr11EyXsA0lpZmIkHxJc6iJF0yPaLLxGVmo41PuT/FgST5gC+JulBovV4wq7I3L1TKfz8+NTOkFxOkO+mz7UkKZm870gJTICgnw4cd9BomXnq4mS4UHerif6pzIEF+0bhvgLg4ZDL0FeOmFzjgpTuKjAjOFfWGwLL2k=    # GH_TOKEN
    # GH_TOKEN
    - secure: V55rGCcFyxIo3nIByQlxvZIE/hRwCstyvIfqvPXUbcFYwkEe4T6LQBuwXw5MqBMXlB/xwOuWlsG8o7MWYmbMnANG8mLa8/7dLvwqHZdbGOIsTnx5G6GwcPijjnevK91UorgY5y5IU/MvCy6PkkJa7EEzKpocvSe+TjfgDQA1HK7q1GrAIuInVzlv0+q2Z0+BVLJuP2CEr40WlGDEGYQerUQM+ONaRx9XHMLyy05akjevYADb3BD/Unv8xRFaaV5fy9sZfNLZDWUMKpAAzmomuabJSg8eQ+t+dDcZi436t+tvAjb6+B2Ql5fnNPJENkCQqYWlzdHAq/V9ADZhAURowC5zepcfmaLNT/eoEnLFRypoxfpqgxyHSgqdQ7uW6NMLAr8HL/baaMvLrr0vuOMZ3Mvb7XxNsscp/hmeeMAVw2BTSV0CoHnKbC6saMry2Ng+cKQ5qmo9NSHsyriRS51JxB1RA2qtsJrA5lBnLiBMUi5MkYXd3OYr0mUGEvcHYa/Z/Szx/LvOkPCkEvvKpVgTAIm5RGtFuML4bJP379qDd/0ORBwOEA4aFWjKZpePhN5UvjGkdcROGEXB9DtXvM0Q/Oj9zkwYIaJ60kX+0ayufizgk20+m3GzfmSpqSAfyCQjqvcO3s3a+E/561GvbuACtTQr/JIrnToUfXujEbakzIQ=
